site_name: TAIL Documenation
repo_url: https://github.com/yale-nlp/TAIL
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide: userguide.md
  # - About: about.md
theme:
    name: flatly

